// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


let num1 =1, num2=2, next,sum=0;
for (let i = 2; i < 400000; i++) {
  next = num1 + num2;
  num1 = num2;
  num2 = next;
  if(next%2==0){
    sum=sum+next;
  }
}
console.log(sum+2)












//     if(count%2==0){ 
//           sum=count+sum;
//     }
// }   console.log(sum+2);